### ISSUE TITLE
FCS_STG_EXT.2 Key Storage Encryption (and 3)

### ISSUE THREAD

**Issue by robertmclemons** [commoncriteria/gpcp#24]
Document inclusion criteria and the consequences of selections.

**Comment by robertmclemons** [comment]
When do we need to store keys or credentials on the platform?

**Comment by bharvey-dell** [comment]
I would think not unless it was tied to Tennant services.

**Comment by robertmclemons** [comment]
If the platform includes a TPM, wouldn't it store some keys related to attestation?
